spring:
  output:
    ansi:
      enabled: always
  jpa:
      database: MYSQL
      show-sql: true
      hibernate:
        ddl-auto: none
  datasource:
      url: jdbc:mysql://localhost:3306/test
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      platform: mysql

server:
  port: 11111

base:
  howMachOne: 1
  howMachTow: 1
  howMachThree: 1